name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  dbt-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install dbt-duckdb

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          airbnb_analytics:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: data/airbnb.duckdb
                schema: dev
          EOF

      - name: Download raw data
        run: |
          mkdir -p data/raw
          curl -L -o data/raw/listings.csv.gz "https://data.insideairbnb.com/united-kingdom/england/london/2025-09-14/data/listings.csv.gz"
          curl -L -o data/raw/reviews.csv.gz "https://data.insideairbnb.com/united-kingdom/england/london/2025-09-14/data/reviews.csv.gz"
          curl -L -o data/raw/calendar.csv.gz "https://data.insideairbnb.com/united-kingdom/england/london/2025-09-14/data/calendar.csv.gz"
          gunzip data/raw/listings.csv.gz
          gunzip data/raw/reviews.csv.gz
          gunzip data/raw/calendar.csv.gz

      - name: Load raw data
        run: python load_data.py

      - name: dbt build
        run: dbt build

      - name: dbt snapshot
        run: dbt snapshot

      - name: dbt docs generate
        run: dbt docs generate

      - name: Upload docs as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/

  deploy-docs:
    needs: dbt-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

